version: '3.8'

services:
  swarms:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: swarms:latest
    container_name: swarms-container
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      # Add your API keys here or use .env file
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
    working_dir: /app
    command: python -c "import swarms; print('Swarms container is running successfully!')"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import swarms; print('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  swarms-dev:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: swarms:dev
    container_name: swarms-dev-container
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
    working_dir: /app
    command: bash
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  default:
    name: swarms-network
